apiVersion: v1
kind: Pod
metadata:
  name: android
  labels:
    app: android
spec:
  containers:
  - name: android
    image: budtmo/docker-android-x86-11.0
    securityContext:
      privileged: true  
    ports:
    - containerPort: 6080
    - containerPort: 5554
    - containerPort: 5555
    env:
    - name: DEVICE
      value: "Samsung Galaxy S6"
---

apiVersion: v1
kind: Service
metadata:
  name: android-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - port: 6080
    name: serving
    protocol: TCP
  - port: 5555
    name: srv
    protocol: TCP
  - port: 5554
    name: srv2
    protocol: TCP
  selector:
    app: android
